apiVersion: v2
name: tempo
description: Grafana Tempo for distributed tracing
type: application
version: 0.1.0
appVersion: "2.7.2"

dependencies:
  - name: tempo
    version: "1.24.4"
    repository: https://grafana.github.io/helm-charts
