apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: {{ .Values.kafka.name }}-pool
  labels:
    strimzi.io/cluster: {{ .Values.kafka.name }}
spec:
  replicas: {{ .Values.kafka.replicas }}
  roles:
    - controller
    - broker
  storage:
    type: {{ .Values.kafka.storage.type }}
  resources:
    {{- toYaml .Values.kafka.resources | nindent 4 }}
