{{- if .Values.adapter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus.adapterName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
    app.kubernetes.io/component: adapter
spec:
  replicas: {{ .Values.adapter.replicaCount }}
  selector:
    matchLabels:
      {{- include "prometheus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: adapter
  template:
    metadata:
      labels:
        {{- include "prometheus.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: adapter
    spec:
      serviceAccountName: {{ include "prometheus.adapterName" . }}
      containers:
        - name: adapter
          image: "{{ .Values.adapter.image.repository }}:{{ .Values.adapter.tag }}"
          imagePullPolicy: {{ .Values.adapter.image.pullPolicy }}
          args:
            - --secure-port={{ .Values.adapter.service.targetPort }}
            - --cert-dir=/tmp/cert
            - --prometheus-url={{ default (printf "http://%s:%d" (include "prometheus.prometheusName" .) (.Values.prometheus.service.port | int)) .Values.adapter.prometheus.url }}
            - --metrics-relist-interval=1m
            - --v=4
            - --config=/etc/adapter/config.yaml
          ports:
            - name: https
              containerPort: {{ .Values.adapter.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.adapter.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/adapter
            - name: tmp-vol
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: {{ include "prometheus.adapterName" . }}-config
        - name: tmp-vol
          emptyDir: {}
      nodeSelector:
        {{- toYaml .Values.adapter.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.adapter.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.adapter.affinity | nindent 8 }}
{{- end }}
