apiVersion: v1
kind: Service
metadata:
  name: {{ include "flink-autoscale.jmName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    {{- include "flink-autoscale.selectorLabels" . | nindent 4 }}
    component: jobmanager
  ports:
    - name: rpc
      port: {{ .Values.jobManager.service.rpcPort }}
      targetPort: {{ .Values.jobManager.service.rpcPort }}
    - name: web
      port: {{ .Values.jobManager.service.webPort }}
      targetPort: {{ .Values.jobManager.service.webPort }}
      nodePort: {{ .Values.jobManager.service.nodePort }}
