{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "flink-autoscale.tmName" . }}-vertical-pod-autoscaler
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "flink-autoscale.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       "Deployment"
    name:       {{ include "flink-autoscale.tmName" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources:
          {{- range .Values.vpa.controlledResources }}
          - {{ . | quote }}
          {{- end }}
        minAllowed:
          {{- with .Values.vpa.minAllowed }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        maxAllowed:
          {{- with .Values.vpa.maxAllowed }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
{{- end }}
