apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flink-autoscale.tmName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.taskManager.replicas }}
  selector:
    matchLabels:
      {{- include "flink-autoscale.selectorLabels" . | nindent 6 }}
      component: taskmanager
  template:
    metadata:
      labels:
        {{- include "flink-autoscale.selectorLabels" . | nindent 8 }}
        component: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["taskmanager"]
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: {{ include "flink-autoscale.jmName" . }}
            - name: TASK_MANAGER_NUMBER_OF_TASK_SLOTS
              value: "{{ .Values.taskManager.slots }}"
          resources:
            {{- toYaml .Values.taskManager.resources | nindent 12 }}
