apiVersion: v2
name: loki
description: Grafana Loki for log aggregation
type: application
version: 0.1.0
appVersion: "3.4.2"

dependencies:
  - name: loki
    version: "6.52.0"
    repository: https://grafana.github.io/helm-charts
