{{- if .Values.recommender.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vertical-pod-autoscaler.recommenderName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vertical-pod-autoscaler.labels" . | nindent 4 }}
{{- end }}

{{- if .Values.updater.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vertical-pod-autoscaler.updaterName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vertical-pod-autoscaler.labels" . | nindent 4 }}
{{- end }}

{{- if .Values.admissionController.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vertical-pod-autoscaler.admissionControllerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vertical-pod-autoscaler.labels" . | nindent 4 }}
{{- end }}

{{- if .Values.recommender.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vertical-pod-autoscaler.recommenderName" . }}
  labels:
    {{- include "vertical-pod-autoscaler.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "limitranges", "replicationcontrollers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling.k8s.io"]
    resources: ["verticalpodautoscalers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling.k8s.io"]
    resources: ["verticalpodautoscalers/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vertical-pod-autoscaler.recommenderName" . }}
  labels:
    {{- include "vertical-pod-autoscaler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vertical-pod-autoscaler.recommenderName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vertical-pod-autoscaler.recommenderName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}

{{- if .Values.updater.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vertical-pod-autoscaler.updaterName" . }}
  labels:
    {{- include "vertical-pod-autoscaler.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling.k8s.io"]
    resources: ["verticalpodautoscalers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling.k8s.io"]
    resources: ["verticalpodautoscalers/status"]
    verbs: ["get", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vertical-pod-autoscaler.updaterName" . }}
  labels:
    {{- include "vertical-pod-autoscaler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vertical-pod-autoscaler.updaterName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vertical-pod-autoscaler.updaterName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}

{{- if .Values.admissionController.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vertical-pod-autoscaler.admissionControllerName" . }}
  labels:
    {{- include "vertical-pod-autoscaler.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "nodes", "limitranges"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling.k8s.io"]
    resources: ["verticalpodautoscalers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vertical-pod-autoscaler.admissionControllerName" . }}
  labels:
    {{- include "vertical-pod-autoscaler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vertical-pod-autoscaler.admissionControllerName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vertical-pod-autoscaler.admissionControllerName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
