{{- if .Values.recommender.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vertical-pod-autoscaler.recommenderName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vertical-pod-autoscaler.labels" . | nindent 4 }}
    app.kubernetes.io/component: recommender
spec:
  replicas: {{ .Values.recommender.replicaCount }}
  selector:
    matchLabels:
      {{- include "vertical-pod-autoscaler.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: recommender
  template:
    metadata:
      labels:
        {{- include "vertical-pod-autoscaler.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: recommender
    spec:
      serviceAccountName: {{ include "vertical-pod-autoscaler.recommenderName" . }}
      containers:
        - name: recommender
          image: "{{ .Values.image.repository }}-recommender:{{ .Values.recommender.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- range .Values.recommender.args }}
            - {{ . | quote }}
            {{- end }}
            {{- if .Values.recommender.prometheus.enabled }}
            - --prometheus-address={{ .Values.recommender.prometheus.address }}
            - --storage=prometheus
            {{- end }}
          ports:
            - name: metrics
              containerPort: 8942
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health-check
              port: metrics
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health-check
              port: metrics
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.recommender.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.recommender.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.recommender.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.recommender.affinity | nindent 8 }}
{{- end }}
