{{- if .Values.admissionController.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vertical-pod-autoscaler.admissionControllerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vertical-pod-autoscaler.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-controller
spec:
  type: ClusterIP
  selector:
    {{- include "vertical-pod-autoscaler.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: admission-controller
  ports:
    - name: webhook
      port: {{ .Values.admissionController.service.port }}
      targetPort: {{ .Values.admissionController.service.targetPort }}
      protocol: TCP
{{- end }}
